import type { Booking } from "@/lib/types";

export const seedBookings: Array<Omit<Booking, "id" | "createdAt">> = [
  {
    referenceNumber: "341764/09/26/FB",
    facilityName: "Tennis Court A",
    category: "Facility Booking - other",
    eventName: "dd",
    description: "m",
    location: "STD.35.N",
    date: "2026-09-18",
    startTime: "06:00",
    endTime: "07:00",
    status: "IN PROGRESS",
  },
  {
    referenceNumber: "339589/09/26/FB",
    facilityName: "Tennis Court B",
    category: "Facility Booking - other",
    eventName: "corp",
    description: "",
    location: "STD.35.N",
    date: "2026-09-10",
    startTime: "06:00",
    endTime: "07:00",
    status: "RECEIVED",
  },
  {
    referenceNumber: "336428/08/26/FB",
    facilityName: "Tennis Court B",
    category: "Facility Booking - other",
    eventName: "corp",
    description: "",
    location: "STD.35.N",
    date: "2026-08-28",
    startTime: "06:00",
    endTime: "07:00",
    status: "RECEIVED",
  },
  {
    referenceNumber: "332668/08/26/FB",
    facilityName: "Tennis Court A",
    category: "Facility Booking - other",
    eventName: "a",
    description: "",
    location: "STD.35.N",
    date: "2026-08-14",
    startTime: "06:00",
    endTime: "07:00",
    status: "RECEIVED",
  },
  {
    referenceNumber: "329540/07/26/FB",
    facilityName: "Tennis Court B",
    category: "Facility Booking - other",
    eventName: "corp",
    description: "",
    location: "STD.35.N",
    date: "2026-08-02",
    startTime: "07:00",
    endTime: "08:00",
    status: "RECEIVED",
  },
  {
    referenceNumber: "329394/07/26/FB",
    facilityName: "Tennis Court A",
    category: "Facility Booking - other",
    eventName: "niko",
    description: "",
    location: "STD.35.N",
    date: "2026-08-01",
    startTime: "14:00",
    endTime: "15:00",
    status: "RECEIVED",
  },
  {
    referenceNumber: "279780/12/25/HK",
    facilityName: "Housekeeping",
    category: "Housekeeping - Grease Trap",
    eventName: "Grease Trap Maintenance",
    description: "",
    location: "STD.35.N",
    date: "2025-12-15",
    startTime: "10:00",
    endTime: "11:00",
    status: "RECEIVED",
  },
  {
    referenceNumber: "129522/03/24/ENG",
    facilityName: "Engineering",
    category: "Engineering - Closet",
    eventName: "Closet Repair",
    description: "",
    location: "STD.35.N",
    date: "2024-03-30",
    startTime: "10:00",
    endTime: "11:00",
    status: "IN PROGRESS",
  },
  {
    referenceNumber: "127385/03/24/ENG",
    facilityName: "Engineering",
    category: "Engineering - Ceiling",
    eventName: "Ceiling Inspection",
    description: "Follow-up inspection of ceiling panel alignment.",
    location: "STD.35.N",
    date: "2024-04-06",
    startTime: "10:00",
    endTime: "11:00",
    status: "IN PROGRESS",
  },
  {
    referenceNumber: "122162/02/24/ENG",
    facilityName: "Engineering",
    category: "Engineering - Ceiling",
    eventName: "Ceiling Repair",
    description: "",
    location: "STD.35.N",
    date: "2024-02-20",
    startTime: "10:00",
    endTime: "11:00",
    status: "RECEIVED",
  },
];
