import type { Booking } from "@/lib/types";

export const seedBookings: Array<Omit<Booking, "id" | "createdAt">> = [
  {
    referenceNumber: "329394/07/26/FB",
    category: "Facility Booking",
    facilityName: "Tennis Court A",
    eventName: "niko",
    description:
      "Private tennis practice session. Court A reserved for singles play. Please bring your own rackets and non-marking shoes.",
    location: "STD.35.N",
    date: "2026-08-01",
    startTime: "14:00",
    endTime: "15:00",
    status: "NEW",
  },
  {
    referenceNumber: "279780/12/25/HK",
    category: "Housekeeping",
    facilityName: "Housekeeping - Grease Trap",
    eventName: "Grease Trap Maintenance",
    description:
      "Scheduled cleaning and maintenance of the kitchen grease trap.",
    location: "STD.35.N",
    date: "2025-12-15",
    startTime: "10:00",
    endTime: "11:00",
    status: "RECEIVED",
  },
  {
    referenceNumber: "129522/03/24/ENG",
    category: "Engineering",
    facilityName: "Engineering - Closet",
    eventName: "Closet Repair",
    description: "Inspection and repair of the utility closet door hinge.",
    location: "STD.35.N",
    date: "2024-03-30",
    startTime: "10:00",
    endTime: "11:00",
    status: "NEW",
  },
  {
    referenceNumber: "127385/03/24/ENG",
    category: "Engineering",
    facilityName: "Engineering - Ceiling",
    eventName: "Ceiling Inspection",
    description: "Follow-up inspection of ceiling panel alignment.",
    location: "STD.35.N",
    date: "2024-04-06",
    startTime: "10:00",
    endTime: "11:00",
    status: "IN PROGRESS",
  },
  {
    referenceNumber: "122162/02/24/ENG",
    category: "Engineering",
    facilityName: "Engineering - Ceiling",
    eventName: "Ceiling Repair",
    description: "Replacement of damaged ceiling panels near corridor B.",
    location: "STD.35.N",
    date: "2024-02-20",
    startTime: "10:00",
    endTime: "11:00",
    status: "RECEIVED",
  },
];
